### ISSUE TITLE
RAT Unable to Die (And reset) Until end of song?

### ISSUE THREAD

**Issue by zachary523** [semicola/Rap-Ability-Test#10]
Whenever I die while playing Solo in VR, it kills me, but then proceeds to only respawn me at the end of the song, 

This is a problem especially when using deathmatch, Which results with the same glitch, But only The song/chart stops as if I "Died" But it doesn't respawn me, Effectively Hardlocking me where the only escape is to leave and rejoin

Not sure what triggers this to happen, But I think it only happens in vr solo play

**Comment by skedgyedgy** [comment]
-- This isn't a hardlock this is a softlock, but I'll look into it.

**Comment by skedgyedgy** [comment]
-- Can you record a video please?

**Comment by zachary523** [comment]
https://github.com/semicola/Rap-Ability-Test/assets/70669236/2e15b3bb-2734-4960-ac6a-eef84ac1826b

This one shows the inability to reset and only resetting after song

**Comment by zachary523** [comment]
https://github.com/semicola/Rap-Ability-Test/assets/70669236/12820d58-3e8e-4d8b-bebe-8fea60189a9d

And here's the death, Complete with the dev console

**Comment by skedgyedgy** [comment]
-- OH I understand what's happening now, the game is trying to play the deathmatch fail animation but since VR mode has a different GUI setup it's erroring out and freezing. Should be fixed in next update! After the patch this Friday, tell me if this is still occurring. For now just disable Deathmatch mode when playing VR.
